package com.depop.countrypicker;

import android.content.Context;
import android.graphics.drawable.Drawable;
import android.support.annotation.DrawableRes;
import android.support.v7.content.res.AppCompatResources;

import java.util.Locale;

import static com.depop.countrypicker.EmojiUtils.getRegionalIndicatorSymbol;

enum Country {
    /* FR, NL and US are specified first because their flags are also used for other countries */
    FR(R.drawable.ic_fr),
    NL(R.drawable.ic_nl),
    US(R.drawable.ic_us),
    AD(R.drawable.ic_ad),
    AE(R.drawable.ic_ae),
    AF(R.drawable.ic_af),
    AG(R.drawable.ic_ag),
    AI(R.drawable.ic_ai),
    AL(R.drawable.ic_al),
    AM(R.drawable.ic_am),
    AO(R.drawable.ic_ao),
    AQ(R.drawable.ic_aq),
    AR(R.drawable.ic_ar),
    AS(R.drawable.ic_as),
    AT(R.drawable.ic_at),
    AU(R.drawable.ic_au),
    AW(R.drawable.ic_aw),
    AX(R.drawable.ic_ax),
    AZ(R.drawable.ic_az),
    BA(R.drawable.ic_ba),
    BB(R.drawable.ic_bb),
    BD(R.drawable.ic_bd),
    BE(R.drawable.ic_be),
    BF(R.drawable.ic_bf),
    BG(R.drawable.ic_bg),
    BH(R.drawable.ic_bh),
    BI(R.drawable.ic_bi),
    BJ(R.drawable.ic_bj),
    BL(FR.mCountryFlag),
    BM(R.drawable.ic_bm),
    BN(R.drawable.ic_bn),
    BO(R.drawable.ic_bo),
    BQ(NL.mCountryFlag),
    BR(R.drawable.ic_br),
    BS(R.drawable.ic_bs),
    BT(R.drawable.ic_bt),
    BV(R.drawable.ic_bv),
    BW(R.drawable.ic_bw),
    BY(R.drawable.ic_by),
    BZ(R.drawable.ic_bz),
    CA(R.drawable.ic_ca),
    CC(R.drawable.ic_cc),
    CD(R.drawable.ic_cd),
    CF(R.drawable.ic_cf),
    CG(R.drawable.ic_cg),
    CH(R.drawable.ic_ch),
    CI(R.drawable.ic_ci),
    CK(R.drawable.ic_ck),
    CL(R.drawable.ic_cl),
    CM(R.drawable.ic_cm),
    CN(R.drawable.ic_cn),
    CO(R.drawable.ic_co),
    CR(R.drawable.ic_cr),
    CU(R.drawable.ic_cu),
    CV(R.drawable.ic_cv),
    CW(R.drawable.ic_cw),
    CY(R.drawable.ic_cy),
    CZ(R.drawable.ic_cz),
    DE(R.drawable.ic_de),
    DJ(R.drawable.ic_dj),
    DK(R.drawable.ic_dk),
    DM(R.drawable.ic_dm),
    DO(R.drawable.ic_do),
    DZ(R.drawable.ic_dz),
    EC(R.drawable.ic_ec),
    EE(R.drawable.ic_ee),
    EG(R.drawable.ic_eg),
    EH(R.drawable.ic_eh),
    ER(R.drawable.ic_er),
    ES(R.drawable.ic_es),
    ET(R.drawable.ic_et),
    FI(R.drawable.ic_fi),
    FJ(R.drawable.ic_fj),
    FK(R.drawable.ic_fk),
    FM(R.drawable.ic_fm),
    FO(R.drawable.ic_fo),
    GA(R.drawable.ic_ga),
    GB(R.drawable.ic_gb),
    GD(R.drawable.ic_gd),
    GE(R.drawable.ic_ge),
    GF(R.drawable.ic_gf),
    GG(R.drawable.ic_gg),
    GH(R.drawable.ic_gh),
    GI(R.drawable.ic_gi),
    GL(R.drawable.ic_gl),
    GM(R.drawable.ic_gm),
    GN(R.drawable.ic_gn),
    GP(FR.mCountryFlag),
    GQ(R.drawable.ic_gq),
    GR(R.drawable.ic_gr),
    GS(R.drawable.ic_gs),
    GT(R.drawable.ic_gt),
    GU(R.drawable.ic_gu),
    GW(R.drawable.ic_gw),
    GY(R.drawable.ic_gy),
    HK(R.drawable.ic_hk),
    HM(R.drawable.ic_hm),
    HR(R.drawable.ic_hr),
    HT(R.drawable.ic_ht),
    HU(R.drawable.ic_hu),
    ID(R.drawable.ic_id),
    IE(R.drawable.ic_ie),
    IL(R.drawable.ic_il),
    IM(R.drawable.ic_im),
    IN(R.drawable.ic_in),
    IO(R.drawable.ic_io),
    IQ(R.drawable.ic_iq),
    IR(R.drawable.ic_ir),
    IS(R.drawable.ic_is),
    IT(R.drawable.ic_it),
    JE(R.drawable.ic_je),
    JM(R.drawable.ic_jm),
    JO(R.drawable.ic_jo),
    JP(R.drawable.ic_jp),
    KE(R.drawable.ic_ke),
    KG(R.drawable.ic_kg),
    KH(R.drawable.ic_kh),
    KI(R.drawable.ic_ki),
    KM(R.drawable.ic_km),
    KN(R.drawable.ic_kn),
    KP(R.drawable.ic_kp),
    KR(R.drawable.ic_kr),
    KW(R.drawable.ic_kw),
    KY(R.drawable.ic_ky),
    KZ(R.drawable.ic_kz),
    LA(R.drawable.ic_la),
    LB(R.drawable.ic_lb),
    LC(R.drawable.ic_lc),
    LI(R.drawable.ic_li),
    LK(R.drawable.ic_lk),
    LR(R.drawable.ic_lr),
    LS(R.drawable.ic_ls),
    LT(R.drawable.ic_lt),
    LU(R.drawable.ic_lu),
    LV(R.drawable.ic_lv),
    LY(R.drawable.ic_ly),
    MA(R.drawable.ic_ma),
    MC(R.drawable.ic_mc),
    MD(R.drawable.ic_md),
    ME(R.drawable.ic_me),
    MF(R.drawable.ic_mf),
    MG(R.drawable.ic_mg),
    MH(R.drawable.ic_mh),
    MK(R.drawable.ic_mk),
    ML(R.drawable.ic_ml),
    MM(R.drawable.ic_mm),
    MN(R.drawable.ic_mn),
    MO(R.drawable.ic_mo),
    MP(R.drawable.ic_mp),
    MQ(FR.mCountryFlag),
    MR(R.drawable.ic_mr),
    MS(R.drawable.ic_ms),
    MT(R.drawable.ic_mt),
    MU(R.drawable.ic_mu),
    MV(R.drawable.ic_mv),
    MW(R.drawable.ic_mw),
    MX(R.drawable.ic_mx),
    MY(R.drawable.ic_my),
    MZ(R.drawable.ic_mz),
    NA(R.drawable.ic_na),
    NC(FR.mCountryFlag),
    NE(R.drawable.ic_ne),
    NF(R.drawable.ic_nf),
    NG(R.drawable.ic_ng),
    NI(R.drawable.ic_ni),
    NO(R.drawable.ic_no),
    NP(R.drawable.ic_np),
    NR(R.drawable.ic_nr),
    NU(R.drawable.ic_nu),
    NZ(R.drawable.ic_nz),
    OM(R.drawable.ic_om),
    PA(R.drawable.ic_pa),
    PE(R.drawable.ic_pe),
    PF(R.drawable.ic_pf),
    PG(R.drawable.ic_pg),
    PH(R.drawable.ic_ph),
    PK(R.drawable.ic_pk),
    PL(R.drawable.ic_pl),
    PM(FR.mCountryFlag),
    PN(R.drawable.ic_pn),
    PR(R.drawable.ic_pr),
    PS(R.drawable.ic_ps),
    PT(R.drawable.ic_pt),
    PW(R.drawable.ic_pw),
    PY(R.drawable.ic_py),
    QA(R.drawable.ic_qa),
    RE(FR.mCountryFlag),
    RO(R.drawable.ic_ro),
    RS(R.drawable.ic_rs),
    RU(R.drawable.ic_ru),
    RW(R.drawable.ic_rw),
    SA(R.drawable.ic_sa),
    SB(R.drawable.ic_sb),
    SC(R.drawable.ic_sc),
    SD(R.drawable.ic_sd),
    SE(R.drawable.ic_se),
    SG(R.drawable.ic_sg),
    SH(R.drawable.ic_sh),
    SI(R.drawable.ic_si),
    SJ(R.drawable.ic_sj),
    SK(R.drawable.ic_sk),
    SL(R.drawable.ic_sl),
    SM(R.drawable.ic_sm),
    SN(R.drawable.ic_sn),
    SO(R.drawable.ic_so),
    SR(R.drawable.ic_sr),
    SS(R.drawable.ic_ss),
    ST(R.drawable.ic_st),
    SV(R.drawable.ic_sv),
    SX(R.drawable.ic_sx),
    SY(R.drawable.ic_sy),
    SZ(R.drawable.ic_sz),
    TC(R.drawable.ic_tc),
    TD(R.drawable.ic_td),
    TF(R.drawable.ic_tf),
    TG(R.drawable.ic_tg),
    TH(R.drawable.ic_th),
    TJ(R.drawable.ic_tj),
    TK(R.drawable.ic_tk),
    TL(R.drawable.ic_tl),
    TM(R.drawable.ic_tm),
    TN(R.drawable.ic_tn),
    TO(R.drawable.ic_to),
    TR(R.drawable.ic_tr),
    TT(R.drawable.ic_tt),
    TV(R.drawable.ic_tv),
    TW(R.drawable.ic_tw),
    TZ(R.drawable.ic_tz),
    UA(R.drawable.ic_ua),
    UG(R.drawable.ic_ug),
    UM(US.mCountryFlag),
    UY(R.drawable.ic_uy),
    UZ(R.drawable.ic_uz),
    VA(R.drawable.ic_va),
    VC(R.drawable.ic_vc),
    VE(R.drawable.ic_ve),
    VG(R.drawable.ic_vg),
    VI(R.drawable.ic_vi),
    VN(R.drawable.ic_vn),
    VU(R.drawable.ic_vu),
    WF(US.mCountryFlag),
    WS(R.drawable.ic_ws),
    YE(R.drawable.ic_ye),
    YT(FR.mCountryFlag),
    ZA(R.drawable.ic_za),
    ZM(R.drawable.ic_zm),
    ZW(R.drawable.ic_zw);

    private final int mCountryFlag;

    Country(@DrawableRes final int countryFlag) {
        mCountryFlag = countryFlag;
    }

    @DrawableRes
    public int getCountryFlag() {
        return mCountryFlag;
    }

    public Drawable getFlagDrawable(final Context context) {
        return AppCompatResources.getDrawable(context, mCountryFlag);
    }

    public String getCountryName() {
        return new Locale(Locale.getDefault().getLanguage(), name()).getDisplayCountry();
    }

    public String getEmojiFlag() {
        return getRegionalIndicatorSymbol(name().charAt(0)) + getRegionalIndicatorSymbol(name().charAt(1));
    }
}
